# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiningOAM', '0003_auto_20160107_1457'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='DiningOAM_adminuser',
        ),
    ]
