# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiningOAM', '0004_auto_20160107_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAdminuser',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_super_admin', models.IntegerField()),
                ('house_id', models.CharField(max_length=36)),
                ('house_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_adminuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMealPrice',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('house_id', models.CharField(max_length=36)),
                ('source_id', models.CharField(max_length=36)),
                ('add_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_meal_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WechatContext',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('context_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'wechat_context',
                'managed': False,
            },
        ),
    ]
